// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqoI09kz5ZojHSQ_dWe2f8a-qTX-FfRi0',
    appId: '1:626075388754:web:88cf804b864b854845c88b',
    messagingSenderId: '626075388754',
    projectId: 'cool-85eea',
    authDomain: 'cool-85eea.firebaseapp.com',
    storageBucket: 'cool-85eea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbSDkrAe4n3_ZbbO-GlG-LoeZLa4PelHA',
    appId: '1:626075388754:android:d2b59a2b71492a2b45c88b',
    messagingSenderId: '626075388754',
    projectId: 'cool-85eea',
    storageBucket: 'cool-85eea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgYHscr5jk_fGPPJSedtfp4b2C9_iVBiY',
    appId: '1:626075388754:ios:87e828a5f2b7092a45c88b',
    messagingSenderId: '626075388754',
    projectId: 'cool-85eea',
    storageBucket: 'cool-85eea.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgYHscr5jk_fGPPJSedtfp4b2C9_iVBiY',
    appId: '1:626075388754:ios:87e828a5f2b7092a45c88b',
    messagingSenderId: '626075388754',
    projectId: 'cool-85eea',
    storageBucket: 'cool-85eea.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqoI09kz5ZojHSQ_dWe2f8a-qTX-FfRi0',
    appId: '1:626075388754:web:9fd7ff6d5f59bfcc45c88b',
    messagingSenderId: '626075388754',
    projectId: 'cool-85eea',
    authDomain: 'cool-85eea.firebaseapp.com',
    storageBucket: 'cool-85eea.firebasestorage.app',
  );
}
